FROM node:22-alpine3.19

WORKDIR /app

# Install Python, make, and g++ (build tools needed for bcrypt)
RUN apk add --no-cache python3 make g++

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
# COPY tools ./tools
RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4002

CMD [ "npm", "run", "dev" ]
